Generated Unit Tests for AsyncEnumrableExtensions
unosquare/swan pull request #271
Opened 2022-08-30 16:49 UTC by Brianx03

Generated Unit Tests for AsyncEnumrableExtensions}

https://github.com/unosquare/swan/issues/270

2022-08-31 13:29 UTC, geoperez requested changes
Let's talk about this.

2022-09-02 13:13 UTC, geoperez requested changes

2022-09-02 13:13 UTC, geoperez commented on test/Swan.Test/ConnectionExtensionsTest.cs
> +        var scalar = await conn.ExecuteScalarAsync("select Name, ProjectScope, ProjectType from Projects");
This query is kinda wrong. When you fetch a scalar query, it should return only one value. And you are selecting multiple columns.

2022-09-13 16:49 UTC, geoperez approved these changes

2022-09-13 17:14 UTC, oscarfgq approved these changes

2022-09-13 17:16 UTC, merged